ENT_KEY2VAL = {'ability': ['play instrument', 'speak language'], 'activity': ['acting', 'archery', 'badminton', 'baking', 'baseball', 'basketball', 'billiards', 'bird watching', 'bowling', 'camping', 'cheerleading', 'chess', 'climbing', 'coloring', 'cooking', 'creative writing', 'crocheting', 'curling', 'cycling', 'dance', 'dancing', 'darts', 'drama', 'drawing', 'driving', 'electronics', 'fashion', 'field hockey', 'fishing', 'flying', 'gardening', 'go', 'golfing', 'gymnastics', 'hiking', 'horseback riding', 'hunting', 'ice hockey', 'indoors', 'jogging', 'kayaking', 'knitting', 'learning', 'magic', 'martial arts', 'model building', 'outdoors', 'painting', 'pet', 'photography', 'poker', 'pottery', 'puzzles', 'racquetball', 'reading', 'rock climbing', 'rugby', 'running', 'scuba diving', 'sculpting', 'sewing', 'shoes', 'shooting', 'shopping', 'singing', 'skateboarding', 'sketching', 'skiing', 'skydiving', 'snowboarding', 'stamp collecting', 'surfing', 'swimming', 'taekwondo', 'tennis', 'travel', 'traveling', 'vacation', 'video games', 'vintage cars', 'volleyball', 'walking', 'watching movies', 'watching television', 'water sports', 'working out', 'whittling', 'wrestling', 'writing', 'yoga'], 'animal': ['bass', 'bat', 'bear', 'bee', 'bird', 'butterfly', 'cat', 'catfish', 'cattle', 'chicken', 'cow', 'crab', 'deer', 'dog', 'dragon', 'duck', 'eagle', 'ferret', 'fish', 'fly', 'fox', 'gorilla', 'hippopotamus', 'horse', 'iguana', 'impala', 'jaguar', 'kite', 'koala', 'koi', 'lion', 'lizard', 'lobster', 'monkey', 'owl', 'panda', 'parakeet', 'parrot', 'pig', 'pony', 'rat', 'reptile', 'salmon', 'shrimp', 'skunk', 'snake', 'sole', 'swallow', 'swift', 'tiger', 'trout', 'tuna', 'wolf', 'zebra'], 'color': ['aqua', 'black', 'blue', 'brown', 'burnt umber', 'chartreuse', 'chocolate', 'cream', 'crimson', 'dark', 'eggplant', 'emerald', 'gold', 'green', 'grey', 'hot pink', 'indigo', 'lavender', 'lemon', 'lilac', 'magenta', 'maroon', 'mustard', 'olive', 'orange', 'pale', 'pink', 'purple', 'rainbow', 'red', 'rose', 'salmon', 'scarlet', 'silver', 'spectrum', 'tan', 'tangerine', 'teal', 'tomato', 'turquoise', 'umber', 'white', 'yellow'], 'citystate': ['alabama', 'alaska', 'atlanta', 'austin', 'baltimore', 'baton rouge', 'boston', 'buffalo', 'california', 'chicago', 'colorado', 'dallas', 'davenport', 'detroit', 'florida', 'georgia', 'grand rapids', 'hawaii', 'hollywood', 'houston', 'illinois', 'indiana', 'jacksonville', 'kansas', 'kentucky', 'las vegas', 'los angeles', 'louisiana', 'maine', 'maryland', 'miami', 'michigan', 'minnesota', 'missouri', 'mobile', 'nashville', 'nevada', 'new hampshire', 'new mexico', 'new orleans', 'new york', 'normal', 'north carolina', 'north dakota', 'ohio', 'ontario', 'orange', 'oregon', 'orlando', 'pennsylvania', 'philadelphia', 'pittsburgh', 'portland', 'puerto rico', 'reading', 'san diego', 'san francisco', 'santa cruz', 'seattle', 'springfield', 'sterling heights', 'syracuse', 'tennessee', 'texas', 'vancouver', 'vermont', 'virginia', 'washington', 'wisconsin', 'york'], 'country': ['algeria', 'argentina', 'australia', 'austria', 'barbados', 'canada', 'china', 'cuba', 'denmark', 'egypt', 'france', 'georgia', 'germany', 'greece', 'iceland', 'india', 'italy', 'jamaica', 'japan', 'mexico', 'saudi arabia', 'spain', 'sweden', 'tanzania', 'united states'], 'company': ['amazon', 'apple', 'best buy', 'facebook', 'google', 'home depot', 'ibm', 'kroger', 'microsoft', 'netflix', 'nike', 'nordstrom', 'pantry', 'popular', 'safeway', 'starbucks', 'target', ''], 'cuisine': ['american cuisine', 'argentina cuisine', 'chinese cuisine', 'french cuisine', 'indian cuisine', 'italian cuisine', 'japanese cuisine', 'louisiana cuisine', 'mexican cuisine', ''], 'degree_type': ['associate', 'bachelors', 'masters', 'phd', 'graduate', 'undergraduate', 'doctoral', 'md', 'jd', 'mba', ''], 'drink': ['beer', 'cab', 'chardonnay', 'chartreuse', 'chocolate', 'coffee', 'coke', 'iced tea', 'liquor', 'maple syrup', 'orange juice', 'red wine', 'scotch', 'vinegar', 'water', 'whiskey'], 'family': ['aunt', 'brother', 'child', 'children', 'daughter', 'father', 'grandchild', 'grandchildren', 'grandfather', 'grandmother', 'grandson', 'husband', 'identical twin', 'mother', 'nephew', 'niece', 'partner', 'sibling', 'sister', 'son', 'spouse', 'triplets', 'twin brother', 'twin sister', 'twins', 'uncle', 'wife'], 'food': ['apple', 'apples', 'asparagus', 'bacon', 'bagels', 'bake', 'baked goods', 'barbecue', 'barley', 'bass', 'bean', 'beans', 'beef', 'beet', 'beets', 'bird', 'birds', 'biscuit', 'bowl', 'brain', 'brat', 'bread', 'breakfast', 'breakfast food', 'brisket', 'broccoli', 'brownies', 'brunch', 'buffalo', 'bun', 'burrito', 'butter', 'cake', 'cakes', 'candy', 'caramel', 'carrots', 'catfish', 'cheddar', 'cheese', 'cheesecake', 'chef', 'cherry', 'chew', 'chicken', 'chickens', 'chili', 'chili peppers', 'chilli', 'chips', 'chocolate', 'chocolate bars', 'chocolate cake', 'chow', 'citrus', 'coffee', 'cook', 'cookie', 'cookies', 'corn', 'crab', 'crawdads', 'cream', 'crust', 'cuisine', 'cupcake', 'cupcakes', 'cut', 'dairy', 'date', 'dates', 'delicious', 'dessert', 'diet', 'diner', 'dinner', 'dip', 'dish', 'dog', 'dog biscuit', 'dogs', 'dressing', 'drink', 'dry', 'duck', 'eat', 'eater', 'egg', 'eggplant', 'empire', 'entree', 'fast', 'fat', 'fire', 'fish', 'food', 'frank', 'french fries', 'fried', 'fries', 'frosting', 'fruit', 'fry', 'game', 'games', 'ginger', 'ginger snaps', 'glasses', 'green', 'green beans', 'green tea', 'greens', 'grub', 'ham', 'hamburger', 'hamburgers', 'heart', 'hearts', 'hens', 'herbs', 'honey', 'hot', 'hot dog', 'hotcakes', 'hotdogs', 'hummus', 'hungry', 'ice', 'ice cream', 'iced tea', 'jack', 'jalapenos', 'jam', 'juice', 'junk food', 'kale', 'ketchup', 'kitchen', 'knife', 'lasagna', 'leg', 'legs', 'lemon', 'lobster', 'lox', 'lunch', 'macaroni', 'maple syrup', 'mashed potatoes', 'meat', 'meatloaf', 'menu', 'meringue', 'milk', 'mushroom', 'mustard', 'noodles', 'nutritious', 'oatmeal', 'oats', 'oil', 'olive', 'omnivore', 'onion', 'orange', 'oranges', 'order', 'pancakes', 'pasta', 'peanut', 'peas', 'pecan', 'pecan pie', 'pepper', 'pepperoni', 'peppers', 'pickle', 'picnic', 'pie', 'pita', 'pitcher', 'pizza', 'plate', 'plates', 'plum', 'pop', 'popcorn', 'pork', 'pot', 'potato', 'prawns', 'pretzels', 'produce', 'protein', 'pudding', 'puffs', 'pumpkins', 'punch', 'raspberry', 'ravioli', 'red meat', 'restaurant', 'rice', 'roll', 'rolls', 'round', 'salad', 'salmon', 'salsa', 'salt', 'sauce', 'sausage', 'savory', 'sea bass', 'seafood', 'shellfish', 'shoulders', 'shrimp', 'side', 'snack', 'snaps', 'soda', 'sole', 'soup', 'sour', 'soy', 'spaghetti', 'spices', 'spicy', 'steak', 'steaks', 'sticks', 'stomach', 'sucker', 'sugar', 'sunfish', 'sunflower', 'supper', 'sushi', 'sweet', 'sweets', 'syrup', 'taco', 'takeout', 'tangerine', 'tart', 'tarts', 'tea', 'tofu', 'tomato', 'trout', 'tuna', 'tuna fish', 'vanilla', 'vegetables', 'vinegar', 'vitamin', 'waffle', 'water', 'wedding cakes', 'wonton'], 'gender': ['female', 'male', 'other'], 'general_location': [''], 'job_status': ['employed', 'unemployed', 'seeking employment', ''], 'language': ['arabic', 'chinese', 'english', 'french', 'german', 'irish', 'italian', 'japanese', 'spanish', 'swedish', 'thai'], 'marital': ['married', 'single', 'divorced', 'engaged'], 'media_genres': ['action', 'adventure', 'anime', 'animation', 'biography', 'comedy', 'crime', 'documentary', 'drama', 'family', 'fantasy', 'history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance', 'short', 'sport', 'superhero', 'talk show', 'thriller', 'war', 'western'], 'media_other': [''], 'movie_title': [''], 'music_artist': ['2pac', 'a fine frenzy', 'adam levine', 'alabama', 'america', 'avenged sevenfold', 'backstreet boys', 'beastie boys', 'berlin', 'bob marley', 'boston', 'brand new', 'britney spears', 'bruno mars', 'bulldog', 'cake', 'canvas', 'charlie daniels', 'cher', 'chicago', 'clinic', 'clutch', 'cold', 'counting crows', 'cream', 'creed', 'drake', 'dream', 'eagles', 'ed sheeran', 'electronic', 'europe', 'fall out boy', 'flavour', 'florida georgia line', 'frank ocean', 'frank sinatra', 'future', 'gossip', 'great white', 'guy', 'heart', 'held hostage', 'imagine dragons', 'insane clown posse', 'james', 'jason mraz', 'jimi hendrix', 'justin bieber', 'justin timberlake', 'katy perry', 'kid rock', 'korn', 'kurt cobain', 'lady gaga', 'led zeppelin', 'linkin park', 'live', 'madonna', 'mario', 'maroon 5', 'metallica', 'mick jagger', 'miley cyrus', 'mountain', 'muse', 'nickelback', 'nirvana', 'one direction', 'pearl jam', 'pepper', 'pink floyd', 'pitbull', 'play', 'pnb rock', 'prince', 'queen', 'radiohead', 'rascal flatts', 'rush', 'sun', 'survivor', 'talent', 'tank', 'taylor swift', 'the beatles', 'the chainsmokers', 'the cure', 'the dogs', 'the feeling', 'the game', 'the lumineers', 'the police', 'the pretenders', 'the rolling stones', 'the weekend', 'thunder', 'tim mcgraw', 'too short', 'tool', 'train', 'u2', 'van halen', 'watch me', 'yo gotti'], 'music_genre': ['alternative rock', 'ballet', 'beat', 'black metal', 'blues', 'classic rock', 'classical', 'country', 'dance', 'death metal', 'disney', 'electronic', 'electronic dance', 'emo', 'folk', 'folk metal', 'funk', 'funk rock', 'grunge', 'hard rock', 'heavy metal', 'hip hop', 'house', 'indie', 'island', 'jazz', 'meringue', 'metal', 'modern rock', 'opera', 'orchestra', 'patriotic', 'pop', 'pop punk', 'punk rock', 'rap', 'religious', 'rock', 'rock opera', 'salsa', 'smooth jazz', 'soul', 'soundtrack', 'string', 'symphony', 'tango', 'techno', 'thrash metal', 'vocal', 'western', 'wood', ''], 'music_instrument': ['bass', 'bass guitar', 'bell', 'bow', 'cello', 'clarinet', 'gong', 'guitar', 'horn', 'keyboard', 'piano', 'saw', 'saxophone', 'string instruments', 'strings', 'trumpet', 'tuba', 'violin', 'whistle'], 'noun': [''], 'number': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', 'thousand', 'million', ''], 'organization': ['sports team', 'sports club', 'fraternity', 'sorority', 'hobby club', 'community center', 'other club'], 'person': ['i', 'my brother', 'my father', 'my mother', 'my sister'], 'person_attribute': ['attractive', 'blonde', 'brunette', 'buff', 'cute', 'dark', 'fair', 'fat', 'feminine', 'freckles', 'heavy', 'large', 'light', 'olive', 'overweight', 'pale', 'petite', 'short', 'skinny', 'small', 'tall', 'tan', 'tattooed', 'thick', 'thin', 'tiny', 'well built'], 'person_label': ['carnivore', 'omnivore', 'vegan', 'vegetarian'], 'personality_trait': ['able', 'above average', 'active', 'aggressive', 'amazing', 'ambitious', 'angry', 'anxious', 'artificial', 'artistic', 'aspiring', 'athletic', 'attentive', 'attractive', 'average', 'awesome', 'balanced', 'beautiful', 'bizarre', 'blue', 'bright', 'brilliant', 'buff', 'busy', 'calm', 'careful', 'caring', 'casual', 'civil', 'clean', 'cold', 'colorful', 'competitive', 'complex', 'confident', 'confused', 'conservative', 'constant', 'content', 'conventional', 'cool', 'courteous', 'crafty', 'crazy', 'creative', 'criminal', 'cultured', 'curious', 'cute', 'decent', 'deep', 'delightful', 'dependent', 'depressed', 'determined', 'difficult', 'dirty', 'dishonest', 'distant', 'distrustful', 'dramatic', 'driving', 'drunk', 'dry', 'dull', 'earthy', 'educated', 'energetic', 'excellent', 'exciting', 'experienced', 'fabulous', 'fair', 'firm', 'flashy', 'flexible', 'focused', 'forgetful', 'forgiving', 'formal', 'frank', 'friendly', 'funny', 'gentle', 'genuine', 'good', 'grand', 'great', 'healthy', 'helpful', 'humble', 'immature', 'insecure', 'intelligent', 'interesting', 'intolerant', 'judgmental', 'kind', 'knowledge', 'lazy', 'liberal', 'lively', 'local', 'logical', 'loyal', 'mannered', 'mature', 'mean', 'mild', 'modern', 'motivated', 'musical', 'natural', 'neat', 'nervous', 'neurotic', 'normal', 'obnoxious', 'odd', 'open', 'optimistic', 'organized', 'outgoing', 'passionate', 'passive', 'patient', 'patriotic', 'peaceful', 'perfectionist', 'personable', 'physical', 'picky', 'polite', 'political', 'popular', 'positive', 'powerful', 'practical', 'pretty', 'private', 'proud', 'quick', 'quiet', 'quirky', 'rational', 'relaxed', 'religious', 'reserved', 'respected', 'responsible', 'responsive', 'retiring', 'romantic', 'ruined', 'sad', 'sassy', 'selfish', 'sensible', 'sensitive', 'serious', 'shallow', 'sharing', 'shy', 'simple', 'slow', 'smart', 'smooth', 'sober', 'solid', 'sour', 'spirited', 'sporting', 'stable', 'strict', 'strong', 'stylish', 'sweet', 'talented', 'thinking', 'tidy', 'timid', 'tired', 'tough', 'trendy', 'unhealthy', 'unmotivated', 'unstable', 'unsure', 'upright', 'warm', 'weak', 'willing', 'winning', 'wise', 'witty', 'wonderful'], 'profession': ['accountant', 'actor', 'actress', 'aide', 'ambassador', 'animator', 'artist', 'astronaut', 'athlete', 'attorney', 'author', 'babysitter', 'baker', 'ballerina', 'banker', 'barber', 'baseball player', 'basketball player', 'bowler', 'builder', 'butcher', 'captain', 'carpenter', 'cartographer', 'cashier', 'chauffeur', 'chef', 'clerk', 'coach', 'concierge', 'contractor', 'cook', 'cop', 'dancer', 'dentist', 'designer', 'director', 'disc jockey', 'doctor', 'driver', 'drummer', 'educator', 'electrician', 'engineer', 'entomologist', 'entrepreneur', 'executive', 'explorer', 'farmer', 'firefighter', 'fisherman', 'football player', 'foreman', 'general', 'hairdresser', 'hunter', 'instructor', 'janitor', 'jockey', 'journalist', 'judge', 'landlord', 'lawyer', 'lecturer', 'librarian', 'lifeguard', 'lyricist', 'manager', 'mechanic', 'model', 'musician', 'nurse', 'painter', 'pediatrician', 'performer', 'pharmacist', 'photographer', 'pianist', 'pilot', 'pitcher', 'plumber', 'poet', 'police', 'president', 'prince', 'princess', 'private', 'professor', 'programmer', 'quarterback', 'quilter', 'ranger', 'receptionist', 'reporter', 'restauranteur', 'retailer', 'sailor', 'scientist', 'scout', 'security guard', 'singer', 'soldier', 'star', 'student', 'surgeon', 'swimmer', 'teacher', 'technician', 'tennis player', 'trainer', 'translator', 'travel agent', 'truck driver', 'tutor', 'typist', 'veteran', 'veterinarian', 'violinist', 'waiter', 'waitress', 'welder', 'writer', 'zookeeper', 'zoologist'], 'read_author': ['agatha christie', 'dan brown', 'george orwell', 'jane austen', 'stephen king', 'jk rowling', ''], 'read_genre': ['art', 'biography', 'business', 'christian', 'comics', 'crime', 'ebooks', 'fantasy', 'fiction', 'graphic novels', 'historical fiction', 'history', 'horror', 'music', 'mystery', 'paranormal', 'philosophy', 'poetry', 'psychology', 'religion', 'romance', 'science', 'science fiction', 'sports', 'suspense', 'thriller', 'travel', 'young adult'], 'read_title': [''], 'read_other': [''], 'school_name': ['alabama state', 'army', 'brown', 'davis', 'drake', 'florida state', 'hopkins', 'michigan state', 'navy', 'ohio', 'penn', 'pitt', 'san diego', 'san francisco', 'stanford', 'syracuse', 'umass', 'washington state', 'western', 'williams'], 'school_status': ['graduated', 'graduate student', 'student', ''], 'school_type': ['elementary school', 'middle school', 'high school', 'university', 'graduate school'], 'season': ['spring', 'summer', 'fall', 'winter'], 'sport_type': ['archery', 'arrow', 'athletics', 'badminton', 'baseball', 'basketball', 'baton', 'bicycling', 'billiards', 'bowling', 'boxing', 'canoeing', 'crew', 'cross country', 'curling', 'cycling', 'diving', 'equestrian', 'exercise', 'field hockey', 'fitness', 'football', 'goalie', 'golf', 'gym', 'gymnastics', 'hockey', 'ice hockey', 'jogging', 'jumping', 'karate', 'kayaking', 'martial arts', 'racing', 'racquetball', 'riding', 'rock climbing', 'rowing', 'rugby', 'running', 'scuba', 'skating', 'skeleton', 'skiing', 'sledding', 'snowboarding', 'soccer', 'softball', 'surfing', 'swimming', 'taekwondo', 'tennis', 'throwing', 'unicycle', 'volley ball', 'walking', 'weightlifting', 'wrestling'], 'subject': ['agriculture', 'arts', 'bible', 'biology', 'business', 'business administration', 'chemistry', 'commerce', 'communication', 'computer science', 'criminal justice', 'design', 'education', 'engineering', 'english literature', 'finance', 'history', 'humanities', 'information', 'international business', 'it', 'journalism', 'leadership', 'letters', 'management', 'marketing', 'mathematics', 'music', 'nursing', 'philosophy', 'politics', 'psychology', 'public affairs', 'public relations', 'religion', 'research', 'science', 'statistics', 'surgery', 'teaching', 'technology'], 'time': ['afternoon', 'century', 'day', 'decade', 'early', 'evening', 'everyday', 'future', 'hour', 'late', 'midnight', 'minute', 'moment', 'month', 'morning', 'never', 'night', 'noon', 'now', 'on time', 'overtime', 'past', 'present', 'season', 'second', 'someday', 'soon', 'sunset', 'time', 'today', 'tomorrow', 'tonight', 'twilight', 'week', 'year'], 'vehicle': ['acura', 'aircraft', 'airplane', 'audi', 'auto', 'automobile', 'bentley', 'bicycle', 'bike', 'bmw', 'boat', 'bus', 'cab', 'camper', 'canoe', 'car', 'carriage', 'chevrolet', 'coach', 'compact car', 'convertible', 'cruise ship', 'cycle', 'driver', 'engine', 'ferrari', 'ford', 'hearse', 'honda', 'jaguar', 'junk', 'kayak', 'lexus', 'mini', 'moped', 'motor', 'motorcycle', 'mountain bike', 'paddle', 'pilot', 'plane', 'porsche', 'railroad', 'railway', 'ride', 'rocket', 'rv', 'scooter', 'semi', 'ship', 'sled', 'sports car', 'subway', 'suv', 'tank', 'taxi', 'toyota', 'trailer', 'train', 'truck', 'unicycle', 'van', 'vehicle', 'vessel', 'volkswagen', 'wheel', 'wheelchair', 'wreck', 'zeppelin', ''], 'location': ['appliance store', 'aquarium', 'arcade', 'arena', 'bakery', 'bank', 'bar', 'barbershop', 'bookstore', 'building', 'cabin', 'cafe', 'church', 'cinema', 'clinic', 'coffee shop', 'college', 'deli', 'depot', 'diner', 'electronics store', 'factory', 'farm', 'gallery', 'garage', 'gas station', 'greenhouse', 'grocery store', 'gym', 'hairdresser', 'home', 'hospital', 'hotel', 'house', 'library', 'mall', 'mansion', 'market', 'mill', 'motel', 'movie theater', 'museum', 'music store', 'nursing home', 'park', 'plant', 'power plant', 'prison', 'pub', 'ranch', 'repair shop', 'residence', 'restaurant', 'retailer', 'salon', 'school', 'shelter', 'shop', 'stable', 'station', 'store', 'studio', 'supermarket', 'symphony', 'terminal', 'theater', 'tomb', 'tower', 'travel agent', 'university', 'upholstery shop', 'warehouse', 'zoo'], 'other': ['']}


FEWSHOT_DEMOGRAPHIC_ATTR_ENT_PAIRS = [
    ('place_origin', 'citystate'),
    ('place_origin', 'country'),
    #('place_origin', 'other'),
    ('live_in_citystatecountry', 'citystate'),
    ('live_in_citystatecountry', 'country'),
    #('live_in_citystatecountry', 'other'),
    #('live_in_general', 'other'),
    ('nationality', 'country'),
    ('employed_by_company', 'company'),
    ('employed_by_general', 'location'),
    #('employed_by_general', 'other'),
    ('has_profession', 'profession'),
    #('has_profession', 'other'),
    ('previous_profession', 'profession'),
    #('previous_profession', 'other'),
    ('job_status', 'job_status'),
    ('teach', 'subject'),
    ('teach', 'activity'),
    #('teach', 'other'),
    ('school_status', 'school_status'),
    ('has_degree', 'degree_type'),
    ('has_degree', 'subject'),
    ('attend_school', 'school_name'),
    ('attend_school', 'school_type'),
    #('own', 'other'),
    #('have', 'other'),
    ('have_pet', 'animal'),
    ('have_sibling', 'family'),
    ('have_children', 'family'),
    ('have_family', 'family'),
    ('have_vehicle', 'vehicle'),
    ('physical_attribute', 'person_attribute'),
    ('misc_attribute', 'personality_trait'),
    ('has_age', 'number'),
    ('marital_status', 'marital'),
    ('gender', 'gender'),
    ('other', 'person_label'),
    #('other', 'other'),
    
]

FEWSHOT_PSYCHOGRAPHICS_ATTR_ENT_PAIRS = [
    ('like_food', 'food'),
    ('like_food', 'cuisine'),
    ('like_drink', 'drink'),
    ('like_animal', 'animal'),
    ('like_movie', 'movie_title'),
    ('like_movie', 'media_genres'),
    #('like_movie', 'other'),
    ('like_music', 'music_artist'),
    ('like_music', 'music_genre'),
    ('like_music', 'music_instrument'),
    #('like_music', 'other'),
    ('like_read', 'read_author'),
    ('like_read', 'read_genre'),
    ('like_read', 'read_title'),
    #('like_read', 'other'),
    ('like_sports', 'sport_type'),
    #('like_sports', 'other'),
    ('like_watching', 'media_genres'),
    ('like_activity', 'activity'),
    ('like_goto', 'location'),
    ('dislike', 'activity'),
    ('dislike', 'food'),
    ('dislike', 'drink'),
    ('dislike', 'animal'),
    ('dislike', 'music_artist'),
    ('dislike', 'music_genre'),
    ('dislike', 'music_instrument'),
    ('dislike', 'read_author'),
    ('dislike', 'read_genre'),
    ('dislike', 'sport_type'),
    ('dislike', 'media_genres'),
    #('dislike', 'other'),
    ('favorite_animal', 'animal'),
    ('favorite_food', 'food'),
    ('favorite_color', 'color'),
    ('favorite_book', 'read_author'),
    ('favorite_book', 'read_genre'),
    ('favorite_book', 'read_title'),
    #('favorite_book', 'other'),
    ('favorite_movie', 'movie_title'),
    ('favorite_movie', 'media_genres'),
    #('favorite_movie', 'other'),
    ('favorite_music', 'music_genre'),
    ('favorite_music', 'music_instrument'),
    #('favorite_music', 'other'),
    ('favorite_music_artist', 'music_artist'),
    ('favorite_activity', 'activity'),
    #('favorite_activity', 'other'),
    ('favorite_drink', 'drink'),
    ('favorite_show', 'media_genres'),
    #('favorite_show', 'other'),
    ('favorite_place', 'citystate'),
    ('favorite_place', 'country'),
    #('favorite_place', 'other'),
    ('favorite_hobby', 'activity'),
    ('favorite_season', 'season'),
    ('favorite_sport', 'sport_type'),
    ('has_hobby', 'activity'),
    ('has_hobby', 'sport_type'),
    #('has_hobby', 'other'),
    ('has_ability', 'ability'),
    ('member_of', 'organization'),
    ('want_do', 'ability'),
    ('want_do', 'activity'),
    ('want_do', 'other'),
    ('want_job', 'profession'),
    ('want', 'family'),
    ('want', 'vehicle'),
    ('want', 'person_attribute'),
    ('want', 'personality_trait'),
    #('want', 'other'),
]

FEWSHOT_ALL_ATTR_ENT_PAIRS = {
    'demographic': FEWSHOT_DEMOGRAPHIC_ATTR_ENT_PAIRS,
    'psychographic': FEWSHOT_PSYCHOGRAPHICS_ATTR_ENT_PAIRS
}

FEWSHOT_DEMOGRAPHIC_ATTR = {
    'place_origin|citystate': 'place_origin_citystate',
    'place_origin|country': 'place_origin_country',
    #'place_origin|other': 'place_origin_other',
    'live_in_citystatecountry|citystate': 'live_in_citystatecountry_citystate',
    'live_in_citystatecountry|country': 'live_in_citystatecountry_country',
    #'live_in_citystatecountry|other': 'live_in_citystatecountry_other',
    #'live_in_general|other': 'live_in_general_other',
    'nationality|country': 'nationality_country',
    'employed_by_company|company': 'employed_by_company_company',
    'employed_by_general|location': 'employed_by_general_location',
    #'employed_by_general|other': 'employed_by_general_other',
    'has_profession|profession': 'has_profession_profession',
    #'has_profession|other': 'has_profession_other',
    'previous_profession|profession': 'previous_profession_profession',
    #'previous_profession|other': 'previous_profession_other',
    'job_status|job_status': 'job_status_job_status',
    'teach|subject': 'teach_subject',
    'teach|activity': 'teach_activity',
    #'teach|other': 'teach|other',
    'school_status|school_status': 'school_status_school_status',
    'has_degree|degree_type': 'has_degree_degree_type',
    'has_degree|subject': 'has_degree_subject',
    'attend_school|school_name': 'attend_school_school_name',
    'attend_school|school_type': 'attend_school_school_type',
    #'own|other': 'own_other',
    #'have|other': 'have_other',
    'have_pet|animal': 'have_pet_animal',
    'have_sibling|family': 'have_sibling_family',
    'have_children|family': 'have_children_family',
    'have_family|family': 'have_family_family',
    'have_vehicle|vehicle': 'have_vehicle_vehicle',
    'physical_attribute|person_attribute': 'physical_attribute_person_attribute',
    'misc_attribute|personality_trait': 'misc_attribute_personality_trait',
    'has_age|number': 'has_age_number',
    'marital_status|marital': 'marital_status_marital',
    'gender|gender': 'gender_gender',
    'other|person_label': 'other_person_label',
    #'other|other': 'other_other',

}

FEWSHOT_DEMOGRAPHIC_ATTRMAP = {
    'place_origin_citystate': ['Location | Birthplace', 'city-state'],
    'place_origin_country': ['Location | Birthplace', 'country'],
    'live_in_citystatecountry_citystate': ['Location | Residence', 'city-state'],
    'live_in_citystatecountry_country': ['Location | Residence', 'country'],
    'nationality_country': ['Location | Nationality', 'nationality'],
    'employed_by_company_company': ['Employment | Company', 'company name'],
    'employed_by_general_location': ['Employment | Workplace', 'workplace'],
    'has_profession_profession': ['Employment | Profession', 'profession'],
    'previous_profession_profession': ['Employment | Previous Profession', 'profession'],
    'job_status_job_status': ['Employment | Job Status', 'job status'],
    'teach_subject': ['Employment | Teaching Experience | Subject', 'subject'],
    'teach_activity': ['Employment | Teaching Experience | Activity', 'activity'],
    'school_status_school_status': ['School | Status', 'school status'],
    'has_degree_degree_type': ['School | Degree', 'degree'],
    'has_degree_subject': ['School | Degree | Subject', 'degree subject'],
    'attend_school_school_name': ['School | Name', 'school name'],
    'attend_school_school_type': ['School | Type', 'school type'],
    'have_pet_animal': ['Possession | Animal', 'animal'],
    'have_sibling_family': ['Family Status | Sibling', 'sibling'],
    'have_children_family': ['Family Status | Children', 'children'],
    'have_family_family': ['Family Status', 'family status'],
    'have_vehicle_vehicle': ['Possession | Vehicle', 'vehicle'],
    'physical_attribute_person_attribute': ['Personal Characteristic | Physical Attribute', 'physical attribute'],
    'misc_attribute_personality_trait': ['Personal Characteristic | Personality Trait', 'personality trait'],
    'has_age_number': ['Age', 'age'],
    'marital_status_marital': ['Marital Status', 'marital status'],
    'gender_gender': ['Gender', 'gender'],
    'other_person_label': ['Personal Characteristic | Eating Habit', 'eating habit'],
}

FEWSHOT_PSYCHOGRAPHICS_ATTR = {
    'like_food|food': 'like_food',
    'like_food|cuisine': 'like_food',
    'like_drink|drink': 'like_drink',
    'like_animal|animal': 'like_animal',
    'like_movie|movie_title': 'like_movie_title',
    'like_movie|media_genres': 'like_movie_genre',
    # 'like_movie|other': 'like_movie_other',
    'like_music|music_artist': 'like_music_artist',
    'like_music|music_genre': 'like_music_genre',
    'like_music|music_instrument': 'like_music_instrument',
    #'like_music|other': 'like_music_other',
    'like_read|read_author': 'like_read_author',
    'like_read|read_genre': 'like_read_genre',
    'like_read|read_title': 'like_read_title',
    #'like_read|other': 'like_read_other',
    'like_sports|sport_type': 'like_sport',
    #'like_sports|other': 'like_sport_other',
    'like_watching|media_genres': 'like_watching',
    'like_activity|activity': 'like_activity',
    'like_goto|location': 'like_goto',
    'favorite_food|food': 'favorite_food',
    'favorite_color|color': 'favorite_color',
    'favorite_book|read_author': 'favorite_read_author',
    'favorite_book|read_genre': 'favorite_read_genre',
    'favorite_book|read_title': 'favorite_read_title',
    #'favorite_book|other': 'favorite_read_other',
    'favorite_movie|movie_title': 'favorite_movie_title',
    'favorite_movie|media_genres': 'favorite_movie_genre',
    #'favorite_movie|other': 'favorite_movie_other',
    'favorite_music|music_genre': 'favorite_music_genre',
    'favorite_music|music_instrument': 'favorite_music_instrument',
    #'favorite_music|other': 'favorite_music_other',
    'favorite_music_artist|music_artist': 'favorite_music_artist',
    'favorite_activity|activity': 'favorite_activity',
    #'favorite_activity|other': 'favorite_other',
    'favorite_drink|drink': 'favorite_drink',
    'favorite_show|media_genres': 'favorite_show',
    #'favorite_show|other': 'favorite_show_other'
    'favorite_place|citystate': 'favorite_place',
    'favorite_place|country': 'favorite_place',
    #'favorite_place|other': 'favorite_place',
    'favorite_hobby|activity': 'favorite_hobby',
    'favorite_season|season': 'favorite_season',
    'favorite_animal|animal': 'favorite_animal',
    'favorite_sport|sport_type': 'favorite_sport',
    'dislike|activity': 'dislike_activity',
    'dislike|food': 'dislike_food',
    'dislike|drink': 'dislike_drink',
    'dislike|animal': 'dislike_animal',
    'dislike|music_artist': 'dislike_music_artist',
    'dislike|music_genre': 'dislike_music_genre',
    'dislike|music_instrument': 'dislike_music_instrument',
    'dislike|read_author': 'dislike_read_author',
    'dislike|read_genre': 'dislike_read_genre',
    'dislike|sport_type': 'dislike_sport_type',
    'dislike|media_genres': 'dislike_media_genre',
    #'dislike|other': 'dislike_other',
    'has_hobby|activity': 'has_hobby_activity',
    'has_hobby|sport_type': 'has_hobby_sport_type',
    #'has_hobby|other': 'has_hobby_other',
    'has_ability|ability': 'has_ability_ability',
    'member_of|organization': 'member_of_organization',
    'want_do|ability': 'want_do_ability',
    'want_do|activity': 'want_do_activity',
    #'want_do|other': 'want_do_other',
    'want_job|profession': 'want_job_profession',
    #'want|family': 'want_family',
}

FEWSHOT_PSYCHOGRAPHICS_ATTRMAP = {
    'like_food': ['Preference | Food', 'food'],
    'like_drink': ['Preference | Drink', 'drink'],
    'like_animal': ['Preference | Animal', 'animal'],
    'like_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    'like_music_genre': ['Preference | Music | Genre', 'music genre'],
    'like_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'like_music_artist': ['Preference | Music | Artist', 'music artist'],
    'like_read_author': ['Preference | Book | Author', 'book author'],
    'like_read_genre': ['Preference | Book | Genre', 'book genre'],
    'like_sport': ['Preference | Sport', 'sport'],
    'like_goto': ['Preference | Location', 'location'],
    'like_watching': ['Preference | Media Genre', 'media genre'],
    'like_activity': ['Preference | Activity', 'acitivity'],
    'favorite_color': ['Preference | Color', 'color'],
    'favorite_food': ['Preference | Food', 'food'],
    'favorite_read_author': ['Preference | Book | Author', 'book author'],
    'favorite_read_genre': ['Preference | Book | Genre', 'book genre'],
    'favorite_read_title': ['Preference | Book | Title', 'book title'],
    'favorite_movie_title': ['Preference | Movie | Title', 'movie_title'],
    'favorite_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    'favorite_music_genre': ['Preference | Music | Genre', 'music genre'],
    'favorite_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'favorite_music_artist': ['Preference | Music | Artist', 'music artist'],
    'favorite_activity': ['Preference | Activity', 'acitivity'],
    'favorite_drink': ['Preference | Drink', 'drink'],
    'favorite_show': ['Preference | Show', 'show'],
    'favorite_place': ['Preference | Place', 'place'],
    'favorite_hobby': ['Preference | Hobby', 'hobby'],
    'favorite_season': ['Preference | Season', 'season'],
    'favorite_animal': ['Preference | Animal', 'animal'],
    'favorite_sport': ['Preference | Sport', 'sport'],
    'dislike_activity': ['Preference | Activity', 'acitivity'],
    'dislike_food': ['Preference | Food', 'food'],
    'dislike_drink': ['Preference | Drink', 'drink'],
    'dislike_animal': ['Preference | Animal', 'animal'],
    'dislike_music_artist': ['Preference | Music | Artist', 'music artist'],
    'dislike_music_genre': ['Preference | Music | Genre', 'music genre'],
    'dislike_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'dislike_read_author': ['Preference | Book | Author', 'book author'],
    'dislike_read_genre': ['Preference | Book | Genre', 'book genre'],
    'dislike_sport_type': ['Preference | Sport', 'sport'],
    'dislike_media_genre': ['Preference | Media Genre', 'media genre'],
    'has_hobby_activity': ['Hobby | Activity', 'activity'],
    'has_hobby_sport_type': ['Hobby | Sport', 'sport'],
    'has_ability_ability': ['Hobby | Ability', 'ability'],
    'member_of_organization': ['Hobby | Organization', 'organization'],
    'want_job_profession': ['Want | Profession', 'profession'],
    'want_do_activity': ['Want | Activity', 'activity'],
    'want_do_ability': ['Want | Ability', 'ability']
}



TARGET_PSYCHOGRAPHICS_ATTRMAP = {
    'like_color': ['Preference | Color', 'color'],
    'like_food': ['Preference | Food', 'food'],
    'like_drink': ['Preference | Drink', 'drink'],
    'like_animal': ['Preference | Animal', 'animal'],
    'like_movie_title': ['Preference | Movie | Title', 'movie title'],
    'like_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    'like_music_genre': ['Preference | Music | Genre', 'music genre'],
    'like_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'like_music_artist': ['Preference | Music | Artist', 'music artist'],
    'like_book_author': ['Preference | Book | Author', 'book author'],
    'like_book_title': ['Preference | Book | Title', 'book title'],
    'like_book_genre': ['Preference | Book | Genre', 'book genre'],
    'like_sport': ['Preference | Sport', 'sport'],
    'like_season': ['Preference | Season', 'season'],
    'like_hobby': ['Preference | Hobby', 'hobby'],
    'like_activity_show': ['Preference | Show', 'show'],
    'like_activity_place': ['Preference | Place', 'place'],
    'like_acitvity_goto': ['Preference | Location', 'location'],
    'like_activity_watching': ['Preference | Media Genre', 'media genre'],
    #'dislike_color': ['Preference | Color', 'color'],
    #'dislike_food': ['Preference | Food', 'food'],
    #'dislike_drink': ['Preference | Drink', 'drink'],
    #'dislike_animal': ['Preference | Animal', 'animal'],
    #'dislike_movie_title': ['Preference | Movie | Title', 'movie title'],
    #'dislike_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    #'dislike_music_genre': ['Preference | Music | Genre', 'music genre'],
    #'dislike_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    #'dislike_music_artist': ['Preference | Music | Artist', 'music artist'],
    #'dislike_book_author': ['Preference | Book | Author', 'book author'],
    #'dislike_book_title': ['Preference | Book | Title', 'book title'],
    #'dislike_book_genre': ['Preference | Book | Genre', 'book genre'],
    #'dislike_sport': ['Preference | Sport', 'sport'],
    #'dislike_season': ['Preference | Season', 'season'],
    #'dislike_hobby': ['Preference | Hobby', 'hobby'],
    #'dislike_activity_show': ['Preference | Show', 'show'],
    #'dislike_activity_place': ['Preference | Place', 'place'],
    #'dislike_acitvity_goto': ['Preference | Location', 'location'],
    #'dislike_activity_watching': ['Preference | Media Genre', 'media genre'],
    #'favorite_color': ['Preference | Color', 'color'],
    #'favorite_food': ['Preference | Food', 'food'],
    #'favorite_drink': ['Preference | Drink', 'drink'],
    #'favorite_animal': ['Preference | Animal', 'animal'],
    #'favorite_movie_title': ['Preference | Movie | Title', 'movie title'],
    #'favorite_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    #'favorite_music_genre': ['Preference | Music | Genre', 'music genre'],
    #'favorite_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    #'favorite_music_artist': ['Preference | Music | Artist', 'music artist'],
    #'favorite_book_author': ['Preference | Book | Author', 'book author'],
    #'favorite_book_title': ['Preference | Book | Title', 'book title'],
    #'favorite_book_genre': ['Preference | Book | Genre', 'book genre'],
    #'favorite_sport': ['Preference | Sport', 'sport'],
    #'favorite_season': ['Preference | Season', 'season'],
    #'favorite_hobby': ['Preference | Hobby', 'hobby'],
    #'favorite_activity_show': ['Preference | Show', 'show'],
    #'favorite_activity_place': ['Preference | Place', 'place'],
    #'favorite_acitvity_goto': ['Preference | Location', 'location'],
    #'favorite_activity_watching': ['Preference | Media Genre', 'media genre'],
}

TARGET_DEMOGRAPHIC_ATTRMAP = {
    'place_origin_citystate': ['Location | Birthplace', 'city-state'],
    'place_origin_country': ['Location | Birthplace', 'country'],
    'live_in_citystatecountry_citystate': ['Location | Residence', 'city-state'],
    'live_in_citystatecountry_country': ['Location | Residence', 'country'],
    'nationality_country': ['Location | Nationality', 'nationality'],
    'employed_by_company_company': ['Employment | Company', 'company name'],
    'employed_by_general_location': ['Employment | Workplace', 'workplace'],
    'has_profession_profession': ['Employment | Profession', 'profession'],
    'previous_profession_profession': ['Employment | Previous Profession', 'profession'],
    'job_status_job_status': ['Employment | Job Status', 'job status'],
    'teach_subject': ['Employment | Teaching Experience | Subject', 'subject'],
    'teach_activity': ['Employment | Teaching Experience | Activity', 'activity'],
    'school_status_school_status': ['School | Status', 'school status'],
    'has_degree_degree_type': ['School | Degree', 'degree'],
    'has_degree_subject': ['School | Degree | Subject', 'degree subject'],
    'attend_school_school_name': ['School | Name', 'school name'],
    'attend_school_school_type': ['School | Type', 'school type'],
    'have_pet_animal': ['Possession | Animal', 'animal'],
    'have_sibling_family': ['Family Status | Sibling', 'sibling'],
    'have_children_family': ['Family Status | Children', 'children'],
    'have_family_family': ['Family Status', 'family status'],
    'have_vehicle_vehicle': ['Possesion | Vehicle', 'vehicle'],
    'physical_attribute_person_attribute': ['Personal Characteristic | Physical Attribute', 'physical attribute'],
    'misc_attribute_personality_trait': ['Personal Characteristic | Personality Trait', 'personality trait'],
    'has_age_number': ['Age', 'age'],
    'marital_status_marital': ['Marital Status', 'marital status'],
    'gender_gender': ['Gender', 'gender'],
    'other_person_label': ['Personal Characteristic | Eating Habit', 'eating habit'],
    
}

TARGET_ALL_ATTRMAP = {
    'place_origin_citystate': ['Location | Birthplace', 'city-state'],
    'place_origin_country': ['Location | Birthplace', 'country'],
    'live_in_citystatecountry_citystate': ['Location | Residence', 'city-state'],
    'live_in_citystatecountry_country': ['Location | Residence', 'country'],
    'nationality_country': ['Location | Nationality', 'nationality'],
    'employed_by_company_company': ['Employment | Company', 'company name'],
    'employed_by_general_location': ['Employment | Workplace', 'workplace'],
    'has_profession_profession': ['Employment | Profession', 'profession'],
    'previous_profession_profession': ['Employment | Previous Profession', 'profession'],
    'job_status_job_status': ['Employment | Job Status', 'job status'],
    'teach_subject': ['Employment | Teaching Experience | Subject', 'subject'],
    'teach_activity': ['Employment | Teaching Experience | Activity', 'activity'],
    'school_status_school_status': ['School | Status', 'school status'],
    'has_degree_degree_type': ['School | Degree', 'degree'],
    'has_degree_subject': ['School | Degree | Subject', 'degree subject'],
    'attend_school_school_name': ['School | Name', 'school name'],
    'attend_school_school_type': ['School | Type', 'school type'],
    'have_pet_animal': ['Possession | Animal', 'animal'],
    'have_sibling_family': ['Family Status | Sibling', 'sibling'],
    'have_children_family': ['Family Status | Children', 'children'],
    'have_family_family': ['Family Status', 'family status'],
    'have_vehicle_vehicle': ['Possession | Vehicle', 'vehicle'],
    'physical_attribute_person_attribute': ['Personal Characteristic | Physical Attribute', 'physical attribute'],
    'misc_attribute_personality_trait': ['Personal Characteristic | Personality Trait', 'personality trait'],
    'has_age_number': ['Age', 'age'],
    'marital_status_marital': ['Marital Status', 'marital status'],
    'gender_gender': ['Gender', 'gender'],
    'other_person_label': ['Personal Characteristic | Eating Habit', 'eating habit'],
    'like_color': ['Preference | Color', 'color'],
    'like_food': ['Preference | Food', 'food'],
    'like_drink': ['Preference | Drink', 'drink'],
    'like_animal': ['Preference | Animal', 'animal'],
    'like_movie_title': ['Preference | Movie | Title', 'movie title'],
    'like_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    'like_music_genre': ['Preference | Music | Genre', 'music genre'],
    'like_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'like_music_artist': ['Preference | Music | Artist', 'music artist'],
    'like_book_author': ['Preference | Book | Author', 'book author'],
    'like_book_title': ['Preference | Book | Title', 'book title'],
    'like_book_genre': ['Preference | Book | Genre', 'book genre'],
    'like_sport': ['Preference | Sport', 'sport'],
    'like_season': ['Preference | Season', 'season'],
    'like_hobby': ['Preference | Hobby', 'hobby'],
    'like_activity_show': ['Preference | Show', 'show'],
    'like_activity_place': ['Preference | Place', 'place'],
    'like_acitvity_goto': ['Preference | Location', 'location'],
    'like_activity_watching': ['Preference | Media Genre', 'media genre'],
    'physical_symptom': ['Physical Symptom', 'physical symptom'],
    'psychiatric_symptom': ['Psychiatric Symptom', 'psychiatric symptom'],
    'respiratory_disease': ['Respiratory Disease', 'respiratory disease'],
    'digestive_disease': ['Digestive Disease', 'digestive disease']
}

WELLNESS_ATTRMAP = {
    'symptom': []
}

FEWSHOT_ATTRMAP = {    
    'demographic': FEWSHOT_DEMOGRAPHIC_ATTRMAP,
    'psychographic': FEWSHOT_PSYCHOGRAPHICS_ATTRMAP,
    'wellness': WELLNESS_ATTRMAP
}

TARGET_ATTRMAP = {    
    'demographic': FEWSHOT_DEMOGRAPHIC_ATTRMAP,
    'psychographic': TARGET_PSYCHOGRAPHICS_ATTRMAP,
    'wellness': WELLNESS_ATTRMAP
}