TARGET_ALL_ATTRMAP = {
    'place_origin_citystate': ['Location | Birthplace', 'city-state'],
    'place_origin_country': ['Location | Birthplace', 'country'],
    'live_in_citystatecountry_citystate': ['Location | Residence', 'city-state'],
    'live_in_citystatecountry_country': ['Location | Residence', 'country'],
    'nationality_country': ['Location | Nationality', 'nationality'],
    'employed_by_company_company': ['Employment | Company', 'company name'],
    'employed_by_general_location': ['Employment | Workplace', 'workplace'],
    'has_profession_profession': ['Employment | Profession', 'profession'],
    'previous_profession_profession': ['Employment | Previous Profession', 'profession'],
    'job_status_job_status': ['Employment | Job Status', 'job status'],
    'teach_subject': ['Employment | Teaching Experience | Subject', 'subject'],
    'teach_activity': ['Employment | Teaching Experience | Activity', 'activity'],
    'school_status_school_status': ['School | Status', 'school status'],
    'has_degree_degree_type': ['School | Degree', 'degree'],
    'has_degree_subject': ['School | Degree | Subject', 'degree subject'],
    'attend_school_school_name': ['School | Name', 'school name'],
    'attend_school_school_type': ['School | Type', 'school type'],
    'have_pet_animal': ['Possession | Animal', 'animal'],
    'have_sibling_family': ['Family Status | Sibling', 'sibling'],
    'have_children_family': ['Family Status | Children', 'children'],
    'have_family_family': ['Family Status', 'family status'],
    'have_vehicle_vehicle': ['Possession | Vehicle', 'vehicle'],
    'physical_attribute_person_attribute': ['Personal Characteristic | Physical Attribute', 'physical attribute'],
    'misc_attribute_personality_trait': ['Personal Characteristic | Personality Trait', 'personality trait'],
    'has_age_number': ['Age', 'age'],
    'marital_status_marital': ['Marital Status', 'marital status'],
    'gender_gender': ['Gender', 'gender'],
    'other_person_label': ['Personal Characteristic | Eating Habit', 'eating habit'],
    'like_color': ['Preference | Color', 'color'],
    'like_food': ['Preference | Food', 'food'],
    'like_drink': ['Preference | Drink', 'drink'],
    'like_animal': ['Preference | Animal', 'animal'],
    'like_movie_title': ['Preference | Movie | Title', 'movie title'],
    'like_movie_genre': ['Preference | Movie | Genre', 'movie genre'],
    'like_music_genre': ['Preference | Music | Genre', 'music genre'],
    'like_music_instrument': ['Preference | Music | Instrument', 'music instrument'],
    'like_music_artist': ['Preference | Music | Artist', 'music artist'],
    'like_book_author': ['Preference | Book | Author', 'book author'],
    'like_book_title': ['Preference | Book | Title', 'book title'],
    'like_book_genre': ['Preference | Book | Genre', 'book genre'],
    'like_sport': ['Preference | Sport', 'sport'],
    'like_season': ['Preference | Season', 'season'],
    'like_hobby': ['Preference | Hobby', 'hobby'],
    'like_activity_show': ['Preference | Show', 'show'],
    'like_activity_place': ['Preference | Place', 'place'],
    'like_acitvity_goto': ['Preference | Location', 'location'],
    'like_activity_watching': ['Preference | Media Genre', 'media genre'],
    'physical_symptom': ['Physical Symptom', 'physical symptom'],
    'psychiatric_symptom': ['Psychiatric Symptom', 'psychiatric symptom'],
    'respiratory_disease': ['Respiratory Disease', 'respiratory disease'],
    'digestive_disease': ['Digestive Disease', 'digestive disease']
}